name: Cypress tests
run-name: ${{ github.event_name == 'pull_request' && format('Testing on {0}', github.head_ref) || 'Testing on main' }}

on:
  pull_request:
    paths:
      - .github/workflows/cypress.yaml
      - common/**
      - cypress/**
  workflow_dispatch:
    inputs:
      device:
        description: Device
        required: true
        default: 'MacBook'
        type: 'choice'
        options:
          - 'MacBook'
          - 'iPad'
          - 'iPhone'
      browser:
        description: Browser
        required: true
        default: 'chrome'
        type: 'choice'
        options:
          - 'chrome'
          - 'edge'
          - 'electron'
          - 'firefox'

jobs:
  cypress:
    name: Cypress tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    env:
      BROWSER: ${{ inputs.browser || 'chrome' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Cypress tests
        run: yarn cy:run:ci --browser=${{ env.BROWSER }}
        env:
          DEVICE: ${{ inputs.device || 'MacBook' }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-videos
          path: cypress/videos/
          retention-days: 10
